# bash_profile, bash_profile_local, vimrc shortcuts
alias bp="vim ~/.bash/.bash_profile"
alias bpr="source ~/.bash/.bash_profile"
alias bpl="vim ~/.bash_profile_local"
alias bplr="source ~/.bash_profile_local"
alias vrc="vim ~/.vimrc"

# did file
alias did="vim +'normal Go' +'r!date' ~/did.txt"

### terminal
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'
    # -i prompts if overwriting an existing file; -v for verbose

alias mkdir='mkdir -pv'
    # -p creates intermediate directories as required; -v for verbose

alias ls="ls -FGlA1"
alias l="ls"
cd() { builtin cd "$@"; l; }                 # Always list directory contents upon 'cd'

alias f='open -a Finder ./'                  # Opens current directory in MacOS Finder
alias c='clear'                              # Clear terminal display

alias up='cd ../'                            # Go back 1 directory level
alias upp='cd ../../'                        # Go back 2 directory levels

alias grep='grep -n --color=always'
    # -n shows line numbers
    # --color makes sure matches are highlighted

# TODO revisit the usefulness of these
md () { mkdir -p "$1" && cd "$1"; }          # mcd:          Makes new Dir and jumps inside
alias teeout='tee ~/Desktop/terminalOut.txt' # teeout:       Pipe content to file on MacOS Desktop

### git
alias gs="git status"
alias gr="git rebase"
alias ga="git add"
alias gd="git diff"
alias gcm="git commit -m"
alias gdc="git diff --cached"
alias gpo="git push origin"
alias goto="git checkout"
alias gh="open https://github.`(git config remote.origin.url | cut -f2 -d.)`"

### prompt PS1 changes
function prompt {
	local BLACK="\[\033[0;30m\]"
	local BLACKBOLD="\[\033[1;30m\]"
	local RED="\[\033[0;31m\]"
	local REDBOLD="\[\033[1;31m\]"
	local GREEN="\[\033[0;32m\]"
	local GREENBOLD="\[\033[1;32m\]"
	local YELLOW="\[\033[0;33m\]"
	local YELLOWBOLD="\[\033[1;33m\]"
	local BLUE="\[\033[0;34m\]"
	local BLUEBOLD="\[\033[1;34m\]"
	local PURPLE="\[\033[0;35m\]"
	local PURPLEBOLD="\[\033[1;35m\]"
	local CYAN="\[\033[0;36m\]"
	local CYANBOLD="\[\033[1;36m\]"
	local WHITE="\[\033[0;37m\]"
	local WHITEBOLD="\[\033[1;37m\]"
	local RESETCOLOR="\[\e[00m\]"

    # https://github.com/ryanoasis/public-bash-scripts/blob/master/unix-color-codes.sh
	local Time12h="\T"
	local Time12a="\@"
    # path short only shows the direct parent directory
	local PathShort="\w"
	local PathFull="\W"
	local NewLine="\n"
	local Jobs="\j"
    # "$" means this is NOT the root
	local RootOrNot="\$"

	export PS1="$BLUE$PathShort $GREEN$RootOrNot $GREENBOLD\$(git branch 2> /dev/null) $RESETCOLOR"
}
prompt

# this was auto-generated by the nvm installation script
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# this checks for bash_profile_local and sources it; keep this at the end of the file
# add local changes here
if [ -f ~/.bash_profile_local ]; then
	source ~/.bash_profile_local
fi
